title = "Vincent Goulet"
baseURL = "https://vigou3.gitlab.io/programmer-avec-r"
languageCode = "fr-ca"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  pages_home = "https://vigou3.gitlab.io/"
  gitlab = "https://gitlab.com/vigou3"
  repos = "programmer-avec-r"
  file_id = "uploads/835388c64d43a2f70331f4f824e1218a/programmer-avec-r.zip"
  release_notes = "-/releases/"
  custom_css = ["/css/custom.css"]
  background_color_class = "bg-black"
  featured_image = "/images/Xerus_inauris_1.jpg"

  ## Google Fonts integration using the implementation of
  ## https://jeremybise.com/google-fonts-in-hugo-themes/
  ##
  ## See also assets/scss/main.scss; layouts/partials/google-fonts.html;
  ## layouts/_default/baseof.html.
  google_fonts = [
    ["Fira Sans", "300, 300i, 400, 400i, 600, 600i"],
    ["Fira Code", "300"]
  ]
  heading_font = "Fira Sans"
  body_font = "Fira Sans"
  code_font = "Fira Code"
