title = "Vincent Goulet"
baseURL = "https://vigou3.gitlab.io/programmer-avec-r"
languageCode = "fr-ca"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  ## Links
  pages_home = "https://vigou3.gitlab.io/"
  gitlab = "https://gitlab.com/vigou3"
  repos = "programmer-avec-r"
  version = "2021.08"
  zip_id = "uploads/149869dca6e53e5548a79a6516de6f72/programmer-avec-r.zip"
  release_notes = "-/releases/"

  ## Look and feel
  custom_css = ["/css/custom.css"]
  background_color_class = "bg-black"
  featured_image = "/images/Xerus_inauris_1.jpg"
  body_classes = "bg-near-white"

  ## Google Fonts integration using the implementation of
  ## https://jeremybise.com/google-fonts-in-hugo-themes/
  ##
  ## See also assets/scss/main.scss; layouts/partials/google-fonts.html;
  ## layouts/partials/head-additions.html.
  google_fonts = [
    ["Fira Sans", "300, 300i, 400, 400i, 600, 600i"],
    ["Fira Code", "300"]
  ]
  heading_font = "Fira Sans"
  body_font = "Fira Sans"
  code_font = "Fira Code"
